version: '3'
services: 
  ide:
    build: .
    volumes: 
    - idedata:/ide/src/spring
    # - faasdata:/faas
    restart: always
    links: 
    - mdb
    - web
    # - daas
    # faas
    networks: 
      bfast_net:
        ipv4_address: 172.28.1.1
  web:
    build: ./lib/webRuntime/
    ports: 
    - "80:80"
    - "443:443"
    restart: always
    networks: 
      bfast_net:
        ipv4_address: 172.28.1.2
  mdb:
    image: mongo
    volumes:
    - mdbdata:/var/data
    restart: always
    networks: 
      bfast_net:
        ipv4_address: 172.28.1.3
  # daas:
  #   build: ./lib/daasRuntime
  #   restart: always
  #   volumes: 
  #   - daasdata:/daas
  #   networks: 
  #     bfas_net:
  #       ipv4_address: 172.28.1.4
  # faas:
  #   image: ubuntu:bionic
  #   restart: always
  #   volumes: 
  #   - faasdata:/faas
volumes: 
  idedata: {}
  mdbdata: {}
  daasdata: {}
  faasdata: {}
networks: 
  bfast_net:
    ipam: 
      driver: default
      config: 
        - subnet: 172.28.0.0/16
  
