version: '3'
services: 
  ide:
    build: .
    volumes: 
    - idedata:/ide/src/spring
    # - faasdata:/faas
    restart: always
    links: 
    - mdb
    - web
    - daas
    # faas
  web:
    image: nginx
    ports: 
    - "8080:80"
    restart: always
  mdb:
    image: mongo
    volumes:
    - mdbdata:/var/data
    restart: always
  daas:
    image: ubuntu:bionic
    working_dir: /daas
    restart: always
    volumes: 
    - daasdata:/daas
  # faas:
  #   image: ubuntu:bionic
  #   restart: always
  #   volumes: 
  #   - faasdata:/faas
volumes: 
  idedata: {}
  mdbdata: {}
  daasdata: {}
  faasdata: {}
  
